PhotoexpressoBundle\Entity\Device:
    type: entity
    table: Device
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        imei:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        modei:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
