PhotoexpressoBundle\Entity\Password:
    type: entity
    table: Password
    indexes:
        fk_Password_User_idx:
            columns:
                - User_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        pwdSha256:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: pwd_sha256
        datetime:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    oneToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                User_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
