passwd_index:
    path:     /
    defaults: { _controller: "PhotoexpressoBundle:Password:index" }
    methods:  GET

passwd_show:
    path:     /{id}/show
    defaults: { _controller: "PhotoexpressoBundle:Password:show" }
    methods:  GET

passwd_new:
    path:     /new
    defaults: { _controller: "PhotoexpressoBundle:Password:new" }
    methods:  [GET, POST]

passwd_edit:
    path:     /{id}/edit
    defaults: { _controller: "PhotoexpressoBundle:Password:edit" }
    methods:  [GET, POST]

passwd_delete:
    path:     /{id}/delete
    defaults: { _controller: "PhotoexpressoBundle:Password:delete" }
    methods:  DELETE
