print_size_index:
    path:     /
    defaults: { _controller: "PhotoexpressoBundle:Printsize:index" }
    methods:  GET

print_size_show:
    path:     /{id}/show
    defaults: { _controller: "PhotoexpressoBundle:Printsize:show" }
    methods:  GET

print_size_new:
    path:     /new
    defaults: { _controller: "PhotoexpressoBundle:Printsize:new" }
    methods:  [GET, POST]

print_size_edit:
    path:     /{id}/edit
    defaults: { _controller: "PhotoexpressoBundle:Printsize:edit" }
    methods:  [GET, POST]

print_size_delete:
    path:     /{id}/delete
    defaults: { _controller: "PhotoexpressoBundle:Printsize:delete" }
    methods:  DELETE
