promo_index:
    path:     /
    defaults: { _controller: "PhotoexpressoBundle:Promotionnal:index" }
    methods:  GET

promo_show:
    path:     /{id}/show
    defaults: { _controller: "PhotoexpressoBundle:Promotionnal:show" }
    methods:  GET

promo_new:
    path:     /new
    defaults: { _controller: "PhotoexpressoBundle:Promotionnal:new" }
    methods:  [GET, POST]

promo_edit:
    path:     /{id}/edit
    defaults: { _controller: "PhotoexpressoBundle:Promotionnal:edit" }
    methods:  [GET, POST]

promo_delete:
    path:     /{id}/delete
    defaults: { _controller: "PhotoexpressoBundle:Promotionnal:delete" }
    methods:  DELETE
