rights_index:
    path:     /
    defaults: { _controller: "PhotoexpressoBundle:Rights:index" }
    methods:  GET

rights_show:
    path:     /{id}/show
    defaults: { _controller: "PhotoexpressoBundle:Rights:show" }
    methods:  GET

rights_new:
    path:     /new
    defaults: { _controller: "PhotoexpressoBundle:Rights:new" }
    methods:  [GET, POST]

rights_edit:
    path:     /{id}/edit
    defaults: { _controller: "PhotoexpressoBundle:Rights:edit" }
    methods:  [GET, POST]

rights_delete:
    path:     /{id}/delete
    defaults: { _controller: "PhotoexpressoBundle:Rights:delete" }
    methods:  DELETE
