user_action_index:
    path:     /
    defaults: { _controller: "PhotoexpressoBundle:Useractions:index" }
    methods:  GET

user_action_show:
    path:     /{id}/show
    defaults: { _controller: "PhotoexpressoBundle:Useractions:show" }
    methods:  GET

user_action_new:
    path:     /new
    defaults: { _controller: "PhotoexpressoBundle:Useractions:new" }
    methods:  [GET, POST]

user_action_edit:
    path:     /{id}/edit
    defaults: { _controller: "PhotoexpressoBundle:Useractions:edit" }
    methods:  [GET, POST]

user_action_delete:
    path:     /{id}/delete
    defaults: { _controller: "PhotoexpressoBundle:Useractions:delete" }
    methods:  DELETE
