user_rights_index:
    path:     /
    defaults: { _controller: "PhotoexpressoBundle:Userrights:index" }
    methods:  GET

user_rights_show:
    path:     /{id}/show
    defaults: { _controller: "PhotoexpressoBundle:Userrights:show" }
    methods:  GET

user_rights_new:
    path:     /new
    defaults: { _controller: "PhotoexpressoBundle:Userrights:new" }
    methods:  [GET, POST]

user_rights_edit:
    path:     /{id}/edit
    defaults: { _controller: "PhotoexpressoBundle:Userrights:edit" }
    methods:  [GET, POST]

user_rights_delete:
    path:     /{id}/delete
    defaults: { _controller: "PhotoexpressoBundle:Userrights:delete" }
    methods:  DELETE
