user_promo_index:
    path:     /
    defaults: { _controller: "PhotoexpressoBundle:UserPromo:index" }
    methods:  GET

user_promo_show:
    path:     /{id}/show
    defaults: { _controller: "PhotoexpressoBundle:UserPromo:show" }
    methods:  GET

user_promo_new:
    path:     /new
    defaults: { _controller: "PhotoexpressoBundle:UserPromo:new" }
    methods:  [GET, POST]

user_promo_edit:
    path:     /{id}/edit
    defaults: { _controller: "PhotoexpressoBundle:UserPromo:edit" }
    methods:  [GET, POST]

user_promo_delete:
    path:     /{id}/delete
    defaults: { _controller: "PhotoexpressoBundle:UserPromo:delete" }
    methods:  DELETE
