<?php

namespace Proxies\__CG__\PhotoexpressoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orderphotosize extends \PhotoexpressoBundle\Entity\Orderphotosize implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'id', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'number', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'brilliantmat', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'marge', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'messagephoto', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'order', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'photo', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'printsize'];
        }

        return ['__isInitialized__', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'id', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'number', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'brilliantmat', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'marge', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'messagephoto', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'order', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'photo', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Orderphotosize' . "\0" . 'printsize'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orderphotosize $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', [$number]);

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrilliantmat($brilliantmat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrilliantmat', [$brilliantmat]);

        return parent::setBrilliantmat($brilliantmat);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrilliantmat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrilliantmat', []);

        return parent::getBrilliantmat();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarge($marge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarge', [$marge]);

        return parent::setMarge($marge);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarge', []);

        return parent::getMarge();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessagephoto($messagephoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessagephoto', [$messagephoto]);

        return parent::setMessagephoto($messagephoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessagephoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessagephoto', []);

        return parent::getMessagephoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\PhotoexpressoBundle\Entity\Order $order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(\PhotoexpressoBundle\Entity\Photo $photo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrintsize(\PhotoexpressoBundle\Entity\Printsize $printsize = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrintsize', [$printsize]);

        return parent::setPrintsize($printsize);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrintsize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrintsize', []);

        return parent::getPrintsize();
    }

}
