<?php

namespace Proxies\__CG__\PhotoexpressoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Appversioning extends \PhotoexpressoBundle\Entity\Appversioning implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'id', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'version', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'datestart', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'datestop', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'apiversion'];
        }

        return ['__isInitialized__', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'id', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'version', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'datestart', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'datestop', '' . "\0" . 'PhotoexpressoBundle\\Entity\\Appversioning' . "\0" . 'apiversion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Appversioning $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatestart($datestart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatestart', [$datestart]);

        return parent::setDatestart($datestart);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatestart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatestart', []);

        return parent::getDatestart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatestop($datestop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatestop', [$datestop]);

        return parent::setDatestop($datestop);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatestop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatestop', []);

        return parent::getDatestop();
    }

    /**
     * {@inheritDoc}
     */
    public function setApiversion($apiversion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiversion', [$apiversion]);

        return parent::setApiversion($apiversion);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiversion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiversion', []);

        return parent::getApiversion();
    }

}
